VECTOR_DB:
  PATH_TO_FOLDER: !ENV '${MY_HOME}/embeddings/vdb/'
  COLLECTION_NAME: articles
  COLL_FRESH_START: True

INPUT_DATA:
  PATH_TO_FOLDER: !ENV '${MY_HOME}/data/docs'
  N_MAX_DOCS: 5
  DOWNLOAD_FRESH_START: True

PRE_TRAINED_EMB:
  SPARSE_MODEL_NAME: 'naver/splade-cocondenser-ensembledistil'
  DENSE_MODEL_NAME: 'all-MiniLM-L6-v2'

RAG:
  QUERY_REWRITING: False

UI:
  APP_LOG_LEVEL: 'INFO'
  APP_LOG_FORMAT: '%(asctime)s %(levelname)s [%(funcName)s]: %(message)s'
  