VECTOR_DB:
  PATH_TO_FOLDER: !ENV '${MY_HOME}/embeddings/vdb/'
  COLLECTION_NAME: articles
  COLL_FRESH_START: True

INPUT_DATA:
  PATH_TO_FOLDER: !ENV '${MY_HOME}/data/docs'

PRE_TRAINED_EMB:
  SPARSE_MODEL_NAME: 'naver/splade-cocondenser-ensembledistil'
  DENSE_MODEL_NAME: 'all-MiniLM-L6-v2'